language: python
services:
  - docker
before_script: pip install docker-compose
script:
  - docker-compose up --build -d
after_success:
  - if [[ "$TRAVIS_BRANCH" == "main" ]]; then
      docker login -u augustoaccorsi -p $DOCKER_PASSWORD ;
      docker-compose up --build -d ;
      docker tag app augustoaccorsi/app-arqsw-aws ;
      docker tag nginx augustoaccorsi/nginx-arqsw-aws ;
      docker push augustoaccorsi/app-arqsw-aws ;
      docker push augustoaccorsi/nginx-arqsw-aws ;

fi:

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: cloud-native-app
  env: Cloudnativeapp-env
  bucket-name: elasticbeanstalk-sa-east-1-571785655335
  bucket-path: cloud-native-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY