services:

  app:
    image: app
    build: ./app
    container_name: app
    environment:
      - FLASK_ENV=prod
    volumes:
      - "./app:/code"
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - app